"""Not a transactional ish

Revision ID: 347c8828a79f
Revises: 5db9bc623bf8
Create Date: 2023-06-29 09:56:08.331666

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '347c8828a79f'
down_revision = '5db9bc623bf8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('admin', schema=None) as batch_op:
        batch_op.create_unique_constraint(batch_op.f('uq_admin_email'), ['email'])
        batch_op.create_unique_constraint(batch_op.f('uq_admin_first_name'), ['first_name'])
        batch_op.create_unique_constraint(batch_op.f('uq_admin_last_name'), ['last_name'])
        batch_op.create_unique_constraint(batch_op.f('uq_admin_phone_number'), ['phone_number'])
        batch_op.create_unique_constraint(batch_op.f('uq_admin_username'), ['username'])

    with op.batch_alter_table('brand', schema=None) as batch_op:
        batch_op.create_unique_constraint(batch_op.f('uq_brand_name'), ['name'])

    with op.batch_alter_table('category', schema=None) as batch_op:
        batch_op.create_unique_constraint(batch_op.f('uq_category_name'), ['name'])

    with op.batch_alter_table('customer', schema=None) as batch_op:
        batch_op.create_unique_constraint(batch_op.f('uq_customer_email'), ['email'])
        batch_op.create_unique_constraint(batch_op.f('uq_customer_phone_number'), ['phone_number'])
        batch_op.create_unique_constraint(batch_op.f('uq_customer_username'), ['username'])

    with op.batch_alter_table('vendor', schema=None) as batch_op:
        batch_op.create_unique_constraint(batch_op.f('uq_vendor_email'), ['email'])
        batch_op.create_unique_constraint(batch_op.f('uq_vendor_name'), ['name'])
        batch_op.create_unique_constraint(batch_op.f('uq_vendor_phone'), ['phone'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('vendor', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('uq_vendor_phone'), type_='unique')
        batch_op.drop_constraint(batch_op.f('uq_vendor_name'), type_='unique')
        batch_op.drop_constraint(batch_op.f('uq_vendor_email'), type_='unique')

    with op.batch_alter_table('customer', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('uq_customer_username'), type_='unique')
        batch_op.drop_constraint(batch_op.f('uq_customer_phone_number'), type_='unique')
        batch_op.drop_constraint(batch_op.f('uq_customer_email'), type_='unique')

    with op.batch_alter_table('category', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('uq_category_name'), type_='unique')

    with op.batch_alter_table('brand', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('uq_brand_name'), type_='unique')

    with op.batch_alter_table('admin', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('uq_admin_username'), type_='unique')
        batch_op.drop_constraint(batch_op.f('uq_admin_phone_number'), type_='unique')
        batch_op.drop_constraint(batch_op.f('uq_admin_last_name'), type_='unique')
        batch_op.drop_constraint(batch_op.f('uq_admin_first_name'), type_='unique')
        batch_op.drop_constraint(batch_op.f('uq_admin_email'), type_='unique')

    # ### end Alembic commands ###
