"""Updated the Vendor table

Revision ID: 918d401ff5a0
Revises: d8794197547a
Create Date: 2023-07-02 22:36:58.546360

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '918d401ff5a0'
down_revision = 'd8794197547a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('activity', schema=None) as batch_op:
        batch_op.alter_column('content',
               existing_type=sa.TEXT(),
               nullable='False')

    with op.batch_alter_table('vendor', schema=None) as batch_op:
        batch_op.add_column(sa.Column('profile_image', sa.String(length=150), nullable=True))
        batch_op.drop_column('image')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('vendor', schema=None) as batch_op:
        batch_op.add_column(sa.Column('image', sa.VARCHAR(length=150), nullable=True))
        batch_op.drop_column('profile_image')

    with op.batch_alter_table('activity', schema=None) as batch_op:
        batch_op.alter_column('content',
               existing_type=sa.TEXT(),
               nullable=True)

    # ### end Alembic commands ###
