"""Deleted brand and cat image columns

Revision ID: fcb5908901c5
Revises: 918d401ff5a0
Create Date: 2023-07-09 20:48:08.262338

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fcb5908901c5'
down_revision = '918d401ff5a0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('activity', schema=None) as batch_op:
        batch_op.alter_column('content',
               existing_type=sa.TEXT(),
               nullable='False')

    with op.batch_alter_table('brand', schema=None) as batch_op:
        batch_op.drop_column('image')

    with op.batch_alter_table('category', schema=None) as batch_op:
        batch_op.drop_column('image')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('category', schema=None) as batch_op:
        batch_op.add_column(sa.Column('image', sa.VARCHAR(length=150), nullable=False))

    with op.batch_alter_table('brand', schema=None) as batch_op:
        batch_op.add_column(sa.Column('image', sa.VARCHAR(length=150), nullable=False))

    with op.batch_alter_table('activity', schema=None) as batch_op:
        batch_op.alter_column('content',
               existing_type=sa.TEXT(),
               nullable=True)

    # ### end Alembic commands ###
